/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControlCompra;
import Controller.ControlUsuario;
import Model.Usuario;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jo3ld
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        cadastre = new javax.swing.JLabel();
        Pergunta = new javax.swing.JLabel();
        linkLogin = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        msnNomeCompleto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelUsername = new javax.swing.JLabel();
        msnUsername = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        mensagemErroEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        mensagemErroCPF = new javax.swing.JLabel();
        inputCpf = new javax.swing.JTextField();
        inputNomeCompleto = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        mensagemErroTelefone = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        msnSenha = new javax.swing.JLabel();
        inputSenha = new javax.swing.JTextField();
        labelConfirmSenha = new javax.swing.JLabel();
        mensagemErroConfirmSenha = new javax.swing.JLabel();
        inputConfirmSenha = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logoImg = new javax.swing.JLabel();
        logoText = new javax.swing.JLabel();
        backgroundIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(13, 17, 23));
        setName("cadastro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        container.setBackground(new java.awt.Color(13, 17, 23));
        container.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 54, 61), 1, true));
        container.setForeground(new java.awt.Color(48, 54, 61));
        container.setPreferredSize(new java.awt.Dimension(640, 510));

        cadastre.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cadastre.setForeground(new java.awt.Color(255, 255, 255));
        cadastre.setText("Se Cadastre");

        Pergunta.setForeground(new java.awt.Color(255, 255, 255));
        Pergunta.setText("Já possui uma conta?");
        Pergunta.setPreferredSize(new java.awt.Dimension(112, 20));

        linkLogin.setForeground(new java.awt.Color(31, 111, 235));
        linkLogin.setText("Login");
        linkLogin.setPreferredSize(new java.awt.Dimension(30, 20));
        linkLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLoginMouseClicked(evt);
            }
        });

        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome Completo");

        msnNomeCompleto.setPreferredSize(new java.awt.Dimension(90, 20));

        jSeparator1.setForeground(new java.awt.Color(48, 54, 61));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 210));

        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Nome de Usuário");

        msnUsername.setPreferredSize(new java.awt.Dimension(90, 20));

        inputUsername.setBackground(new java.awt.Color(48, 54, 61));
        inputUsername.setForeground(new java.awt.Color(255, 255, 255));
        inputUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        inputUsername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUsernameFocusLost(evt);
            }
        });

        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail");

        mensagemErroEmail.setPreferredSize(new java.awt.Dimension(90, 20));

        inputEmail.setBackground(new java.awt.Color(48, 54, 61));
        inputEmail.setForeground(new java.awt.Color(255, 255, 255));
        inputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        inputEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });

        labelCpf.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf.setText("CPF");

        mensagemErroCPF.setPreferredSize(new java.awt.Dimension(90, 20));

        inputCpf.setBackground(new java.awt.Color(48, 54, 61));
        inputCpf.setForeground(new java.awt.Color(255, 255, 255));
        inputCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputCpf.setCaretColor(new java.awt.Color(255, 255, 255));
        inputCpf.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCpfFocusLost(evt);
            }
        });
        inputCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfActionPerformed(evt);
            }
        });

        inputNomeCompleto.setBackground(new java.awt.Color(48, 54, 61));
        inputNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        inputNomeCompleto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputNomeCompleto.setCaretColor(new java.awt.Color(255, 255, 255));
        inputNomeCompleto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputNomeCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNomeCompletoFocusLost(evt);
            }
        });

        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setText("Telefone");

        mensagemErroTelefone.setPreferredSize(new java.awt.Dimension(90, 20));

        inputTelefone.setBackground(new java.awt.Color(48, 54, 61));
        inputTelefone.setForeground(new java.awt.Color(255, 255, 255));
        inputTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputTelefone.setCaretColor(new java.awt.Color(255, 255, 255));
        inputTelefone.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputTelefone.setVerifyInputWhenFocusTarget(false);
        inputTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputTelefoneFocusLost(evt);
            }
        });

        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha");

        msnSenha.setPreferredSize(new java.awt.Dimension(90, 20));

        inputSenha.setBackground(new java.awt.Color(48, 54, 61));
        inputSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        inputSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        labelConfirmSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmSenha.setText("Confirme sua senha");

        mensagemErroConfirmSenha.setPreferredSize(new java.awt.Dimension(90, 20));

        inputConfirmSenha.setBackground(new java.awt.Color(48, 54, 61));
        inputConfirmSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputConfirmSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(83, 65, 65), 1, true));
        inputConfirmSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        inputConfirmSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputConfirmSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputConfirmSenhaFocusLost(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(31, 111, 235));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(48, 54, 61));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(inputCpf)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensagemErroEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(inputEmail)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msnUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensagemErroCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSenha)
                            .addComponent(inputTelefone)
                            .addComponent(inputConfirmSenha)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msnSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelConfirmSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensagemErroConfirmSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(labelTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensagemErroTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msnNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(inputNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                        .addComponent(Pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cadastre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(msnNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelUsername)
                            .addComponent(msnUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mensagemErroEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCpf)
                            .addComponent(mensagemErroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefone)
                            .addComponent(mensagemErroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(msnSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelConfirmSenha)
                            .addComponent(mensagemErroConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(container);
        container.setBounds(320, 110, 640, 510);

        jPanel2.setOpaque(false);

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo GameRush.png"))); // NOI18N

        logoText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoText.setForeground(new java.awt.Color(255, 255, 255));
        logoText.setText("GameRush");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logoImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoText)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoImg)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logoText)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 0, 250, 100);

        backgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tela de Login.png"))); // NOI18N
        getContentPane().add(backgroundIMG);
        backgroundIMG.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfActionPerformed

    //validações
    public static boolean emailValido(String email) {
        String regex = "^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$";
        return Pattern.matches(regex, email);
    }

    public static boolean telefoneValido(String telefone) {
        telefone = telefone.replaceAll("[\\s()-]", "");
        return telefone.matches("^\\d{10,11}$");
    }

    public static boolean cpfFormatoValido(String cpf) {
        String regex = "^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{11})$";
        return cpf != null && cpf.matches(regex);
    }

    //Métodos de evento
    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        String nomeCompleto = inputNomeCompleto.getText();
    String username = inputUsername.getText();
    String senha = inputSenha.getText();
    String email = inputEmail.getText();
    String telefone = inputTelefone.getText();
    String cpf = inputCpf.getText();
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void linkLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLoginMouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_linkLoginMouseClicked

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        String email = inputEmail.getText();
        if (email.isEmpty()) {
            mensagemErroEmail.setText("Campo não preenchido");
            mensagemErroEmail.setForeground(Color.orange);
        } else if (emailValido(email)) {
            mensagemErroEmail.setText("Válido");
            mensagemErroEmail.setForeground(Color.green);
        } else {
            mensagemErroEmail.setText("Email inválido");
            mensagemErroEmail.setForeground(Color.red);
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCpfFocusLost
        String cpf = inputCpf.getText();
        if (cpf.isEmpty()) {
            mensagemErroCPF.setText("Preencha o campo");
            mensagemErroCPF.setForeground(Color.orange);
        } else if(cpfFormatoValido(cpf)) {
            mensagemErroCPF.setText("Válido");
            mensagemErroCPF.setForeground(Color.green);
        } else{
            mensagemErroCPF.setText("CPF inválido");
            mensagemErroCPF.setForeground(Color.red);
        }
    }//GEN-LAST:event_inputCpfFocusLost

    private void inputTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTelefoneFocusLost
         String telefone = inputTelefone.getText();
        if (telefone.isEmpty()) {
            mensagemErroTelefone.setText("Preencha o campo");
            mensagemErroTelefone.setForeground(Color.orange);
        } else if(telefoneValido(telefone)) {
            mensagemErroTelefone.setText("Válido");
            mensagemErroTelefone.setForeground(Color.green);
        } else{
            mensagemErroTelefone.setText("telefone inválido");
            mensagemErroTelefone.setForeground(Color.red);
        }
    }//GEN-LAST:event_inputTelefoneFocusLost

    private void inputConfirmSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfirmSenhaFocusLost
        String senha = inputSenha.getText();
        String confirmSenha = inputConfirmSenha.getText();
        if (senha.isEmpty()) {
            mensagemErroConfirmSenha.setText("Preencha o campo");
            mensagemErroConfirmSenha.setForeground(Color.orange);
        } else if(senha.equals(confirmSenha)) {
            mensagemErroConfirmSenha.setText("Válido");
            mensagemErroConfirmSenha.setForeground(Color.green);
        } else{
            mensagemErroConfirmSenha.setText("Senha inválida");
            mensagemErroConfirmSenha.setForeground(Color.red);
        }
    }//GEN-LAST:event_inputConfirmSenhaFocusLost

    private void inputNomeCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNomeCompletoFocusLost
        String nome = inputNomeCompleto.getText();
        if (nome.isEmpty()) {
            msnNomeCompleto.setText("Preencha o campo");
            msnNomeCompleto.setForeground(Color.orange);
        } else{
            msnNomeCompleto.setText(" ");
        }
    }//GEN-LAST:event_inputNomeCompletoFocusLost

    private void inputUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameFocusLost
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pergunta;
    private javax.swing.JLabel backgroundIMG;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel cadastre;
    private javax.swing.JPanel container;
    private javax.swing.JTextField inputConfirmSenha;
    private javax.swing.JTextField inputCpf;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNomeCompleto;
    private javax.swing.JTextField inputSenha;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelConfirmSenha;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel linkLogin;
    private javax.swing.JLabel logoImg;
    private javax.swing.JLabel logoText;
    private javax.swing.JLabel mensagemErroCPF;
    private javax.swing.JLabel mensagemErroConfirmSenha;
    private javax.swing.JLabel mensagemErroEmail;
    private javax.swing.JLabel mensagemErroTelefone;
    private javax.swing.JLabel msnNomeCompleto;
    private javax.swing.JLabel msnSenha;
    private javax.swing.JLabel msnUsername;
    // End of variables declaration//GEN-END:variables

}
